# Generated by Django 3.0.2 on 2020-01-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_level'),
        ('account', '0002_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
