# Generated by Django 3.0.2 on 2020-02-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_studentanswer_takenquiz'),
        ('account', '0003_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(through='quiz.TakenQuiz', to='quiz.Quiz'),
        ),
    ]
