# Generated by Django 3.0.2 on 2020-01-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
    ]
