# Generated by Django 3.0.2 on 2020-02-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_studentanswer_takenquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takenquiz',
            options={'verbose_name_plural': 'Taken Quizzes'},
        ),
    ]
