# Generated by Django 3.0.3 on 2026-05-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20260226_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
