# Generated by Django 3.0.2 on 2020-02-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_student_quizzes'),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='words.Deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='account.Student'),
        ),
    ]
