# Generated by Django 3.0.3 on 2020-06-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_practice', models.DateField(auto_now_add=True)),
                ('times_practiced', models.PositiveIntegerField(default=1)),
                ('easy_factor', models.FloatField(default=2.5)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='words.Card')),
            ],
            options={
                'ordering': ['next_practice'],
            },
        ),
    ]
