# Generated by Django 3.0.2 on 2020-02-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
        ('account', '0004_student_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_practice', models.DateField(auto_now_add=True)),
                ('times_practiced', models.PositiveIntegerField(default=1)),
                ('easy_factor', models.FloatField(default=2.5)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
            options={
                'ordering': ['next_practice'],
            },
        ),
    ]
