# Generated by Django 3.0.2 on 2020-02-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('memorisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='words.Card'),
        ),
    ]
