# Generated by Django 3.0.2 on 2020-02-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorisation', '0002_auto_20200205_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='user',
            new_name='student',
        ),
    ]
