# Generated by Django 3.0.3 on 2020-02-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorisation', '0005_auto_20200225_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='student',
        ),
    ]
