# Generated by Django 3.0.3 on 2026-02-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20260226_1047'),
        ('memorisation', '0006_remove_practice_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('due', models.DateField()),
                ('interval', models.IntegerField()),
                ('ease_factor', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('lapses', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='words.Card')),
            ],
            options={
                'db_table': 'card_practice',
                'ordering': ['due'],
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='memorisation.CardPractice')),
            ],
            options={
                'db_table': 'card_reviews',
            },
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('memorisation.cardpractice',),
        ),
    ]
