# Generated by Django 3.0.2 on 2020-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='cards/')),
                ('explanation', models.TextField(blank=True, max_length=500)),
                ('exemple', models.TextField(blank=True, max_length=500)),
                ('translation', models.CharField(blank=True, max_length=55)),
                ('synonymes', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
